version: '3.3'

services:
        i2b2_db:
                build:
                        context: .
                        args:
                                - I2B2_VERSION
                # image: i2b2_db:${I2B2_VERSION}
                image: i2b2_db:latest
                ports:
                        - 5432:5432
                networks:
                        - i2b2_test
                env_file:
                        - .env
                volumes:
                        - i2b2_db_data:/var/lib/postgresql/data

networks:
        i2b2_test:
volumes:
        i2b2_db_data:
